#!/bin/bash

ftype="$(file "$1")"
case "$ftype" in
"$1: Zip archive"*)
   unzip "$1" ;;
"$1: gzip compressed"*)
   gunzip "$1" ;;
"$1: bzip2 compressed"*)
   bunzip "$1" ;;
*) echo "File $1 can not be uncompressed with smartzip";;
esac
